#![allow(clippy::single_component_path_imports)]

/// Simple cli module
pub mod cli;
/// CRUD operations for db
pub mod crud;
/// Models of current db
pub mod models;
/// Autogenerated schema
pub mod schema;

use tracing;
use tracing::Level;
use tracing_subscriber;
use tracing_subscriber::prelude::*;

pub fn set_global_subscriber(
    level: Level,
) -> Result<(), tracing::subscriber::SetGlobalDefaultError> {
    let writer = std::io::stdout.with_max_level(level);
    let layer = tracing_subscriber::fmt::layer()
        .json()
        .with_target(false)
        .flatten_event(true)
        .with_writer(writer);
    let subscriber = tracing_subscriber::Registry::default().with(layer);
    tracing::subscriber::set_global_default(subscriber)
}
