[package]
name = "step_3_11"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full", "fs", "rt-multi-thread"] }
