[package]
name = "step_3_1"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
cucumber = "0.20"
futures = "0.3"

[[test]]
name = "example"
harness = false  # allows Cucumber to print output instead of libtest
